services:
  backend:
    build:
      context: backend 
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    image: python:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
    env_file:
      - ./backend/.env.sample
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        - action: restart
          # target: /app
          path: ./backend/src/

  app:
    build:
      context: static_html 
      dockerfile: static.Dockerfile
    ports:
      - "8000:8000"
      - "3000:8000"
    image: python:latest
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app